### ISSUE TITLE
Re-registering device fails on iOS

### ISSUE THREAD

**Issue by fakir22** [Pushwoosh/pushwoosh-phonegap-plugin#212]
Re-registering device on iOS has no effect. Steps to reproduce:

1. call registerForPushNotifications (device is visible on dashboard counter and it's receiving notifications)
2. call unregisterForPushNotifications at some point
3. call registerForPushNotifications again

Result: device is never registered again until user uninstalls the app. Device doesn't appear on pushwoosh dashboard.

**Comment by tehmooo** [comment]
Same issue on phonegap build - register calls fine, but calling it again produces nothing

**Comment by wfhm** [comment]
Hi, 

Could you please specify your plugin version?

**Comment by fakir22** [comment]
Hi, 

I use the last version 6.2.2 of pushwoosh plugin with latest version of Phonegap  CLI (6.3.x)

**Comment by tehmooo** [comment]
6.2.3 for me, same phonegap cli - it was working for like 10 mins today, then wen't down the sh***** again. Any thoughts? Trying to work out what's broken is driving me nuts.

**Comment by shaders** [comment]
This (https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/commit/af9ea1a3df293be30457ae739e62e626ecec9425) should fix the problem. Please note that if there are any queues on the public API there might be slight delays in registering. As long as you see registerDevice being called in XCode logs - everything is fone.

**Comment by fakir22** [comment]
Unfortunately it still doesn't work. 
Last version 6.4.0 of pushwoosh plugin with Phonegap 6.3.3

I waited over an hour but the device did not showed up again in the pushwoosh admin interface.
